AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FoodOffice Backend - Lambda + API Gateway

Globals:
  Function:
    Timeout: 28
    MemorySize: 512
    Runtime: nodejs20.x
    Environment:
      Variables:
        NODE_ENV: production

Parameters:
  DatabaseHost:
    Type: String
  DatabaseName:
    Type: String
    Default: foodoffice
  DatabaseUser:
    Type: String
    Default: foodoffice
  DatabasePassword:
    Type: String
    NoEcho: true
  JwtSecret:
    Type: String
    NoEcho: true
  SubnetIds:
    Type: CommaDelimitedList
  SecurityGroupId:
    Type: String
  AllowedOrigins:
    Type: String
    Default: "*"
  OAuthServerUrl:
    Type: String
    Default: ""
  ViteAppId:
    Type: String
    Default: ""
  OAuthClientSecret:
    Type: String
    Default: ""
    NoEcho: true
  OwnerOpenId:
    Type: String
    Default: ""

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Metadata:
      # Esto le dice a SAM que compile el TS automáticamente
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "node20"
        Sourcemap: true
        EntryPoints: 
          - lambda.ts
    Properties:
      CodeUri: src/
      Handler: lambda.handler # Se refiere al archivo lambda.js generado
      Environment:
        Variables:
          DATABASE_URL: !Sub 'postgresql://${DatabaseUser}:${DatabasePassword}@${DatabaseHost}:5432/${DatabaseName}'
          JWT_SECRET: !Ref JwtSecret
          NODE_ENV: production
          ALLOWED_ORIGINS: !Ref AllowedOrigins
          OAUTH_SERVER_URL: !Ref OAuthServerUrl
          VITE_APP_ID: !Ref ViteAppId
          OAUTH_CLIENT_SECRET: !Ref OAuthClientSecret
          OWNER_OPEN_ID: !Ref OwnerOpenId
      VpcConfig:
        SecurityGroupIds:
          - !Ref SecurityGroupId
        SubnetIds: !Ref SubnetIds
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: '*'
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /{proxy+}
            Method: ANY
        ApiRoot:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /
            Method: ANY

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins: !Split [",", !Ref AllowedOrigins]
        AllowMethods: [GET, POST, PUT, DELETE, OPTIONS, PATCH]
        AllowHeaders: [Content-Type, Authorization, Cookie]
        AllowCredentials: true
        MaxAge: 3600

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'